Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/GuardClause:
  Enabled: false

Style/WordArray:
  Exclude:
    - 'Rakefile'
    - 'tasks/**/*.rake'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'tasks/**/*.rake'
    - 'spec/**/*.rb'
